name: Dependency review
on:
  pull_request:
  merge_group:
    types: [checks_requested]
permissions: {}
jobs:
  dependency-review:
    runs-on: ubuntu-24.04
    timeout-minutes: 10
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: actions/dependency-review-action@5595ccaf912efad79be6eef63a5619ff05969be3 # v4
